<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;netcoreapp3.1;net5.0;net6.0;net7.0;net8.0;net9.0</TargetFrameworks>
    <Description>Simplifies working with SQL Server databases in .NET Framework, .NET Core and .NET Standard projects</Description>
    <Version>3.0.1.1</Version>
    <Authors>Andrey Gruber</Authors>
    <PackageTags>Database, SQLServer, ADO.NET, .NET, Core, Snandard, Framework</PackageTags>
    <RepositoryUrl>https://github.com/dedpichto/ag.DbData.SqlServer</RepositoryUrl>
    <PackageProjectUrl>https://github.com/dedpichto/ag.DbData.SqlServer</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageReleaseNotes>Updates Syste.Data.SqlClient dependency to the latest verstion (4.90)</PackageReleaseNotes>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>ag.DbData.SqlServer.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>ag.DbData.SqlServer.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove=".gitignore" />
    <None Remove="LICENSE" />
    <None Remove="README.md" />
  </ItemGroup>

  <ItemGroup>
    <None Include="readme.txt" Pack="true" PackagePath="." />
  </ItemGroup>

  <!-- Only reference System.Data.SqlClient for .NET Framework 4.7.2 -->
  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <!-- Only reference Microsoft.Data.SqlClient for .NET Core/.NET 5+ -->
  <ItemGroup Condition="'$(TargetFramework)' != 'net472'">
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="ag.DbData.Abstraction" Version="3.0.0.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.9" />
  </ItemGroup>

</Project>
